package com.entity;

public enum SubCategory {
	BOOTS, CASUAL, FORMALSHOES, SLIDERS, SPORTSSHOES,
	JACKETS, SHIRTS, SWEATSHIRTS_HOODIES, T_SHIRTS, JEANS, TROUSERS, SHORTS,
	CASUAL_SHOES, SLIDERS_FLIP_FLOPS, TOPS_T_SHIRTS, DRESSES, SCHOOL_SHOES,
	SMARTPHONES, LAPTOPS, SMARTWATCHES, HEADPHONES,
	KITCHEN_APPLIANCES, HOME_DECOR, BEDDING,
	SKINCARE, MAKEUP, HAIRCARE,
	WATCHES, SUNGLASSES, BELTS, WALLETS,
	NECKLACES, EARRINGS, RINGS,
	BACKPACKS, HANDBAGS, TRAVEL_LUGGAGE
}
